### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by Richards0nd** [ganlvtech/lua-simple-encrypt#16]
Hello, I would like to know if there is some form of the file not being decrypted ...
Because currently with GameGuardian it is possible to see the code again.
Is there any way not to do that?

**Comment by ganlvtech** [comment]
May be you need ELGGByRevo (Encrypt Lua GG By Revo).
That's a Lua script to encrypt lua script. But it's not opensource. The release is encrypted by itself.
