### ISSUE TITLE
GameGuardian could not be encrypted

### ISSUE THREAD

**Issue by Hazuki-san** [ganlvtech/lua-simple-encrypt#2]
After the website updated, I'm unable to encrypt my script anymore! Could you check it please?

**Comment by ganlvtech** [comment]
Have a try of the latest version. I'm sorry for my mistake. `[1]` is missing after `gg.prompt`.

**Comment by Hazuki-san** [comment]
Thanks! Will check that!

**Comment by aaaazasddfdfdf** [comment]
My brother when encoding and press download to download the file, can you give me the solution or run the encoding files, my operation is wrong

**Comment by aaaazasddfdfdf** [comment]
How to turn on file encryption Please give me an education
