### ISSUE TITLE
deploy issues

### ISSUE THREAD

**Issue by YumeGod** [ganlvtech/lua-simple-encrypt#26]
I use npm run dev to deploy the obfuscator to my server, I can access through localhost:8080, but I cannot access through IP:8080 on my computer, I have checked all firewall settings, but other app can access through IP:8080 , so that means theres no problem with the firewall , should i change any settings ?

**Comment by ganlvtech** [comment]
You can find more details from [StackOverflow: How to get access to webpack-dev-server from devices in local network?](https://stackoverflow.com/questions/35412137/how-to-get-access-to-webpack-dev-server-from-devices-in-local-network/35419631#35419631).

There are several ways.

1. Change [package.json](https://github.com/ganlvtech/lua-simple-encrypt/blob/master/package.json) `webpack-dev-server` to `webpack-dev-server --host=0.0.0.0` and run `npm run dev`.

https://github.com/ganlvtech/lua-simple-encrypt/blob/54b1449a1f662d2893e2673de4f3f2d0599eeee8/package.json#L9

2. Or just run `npm run dev -- --host=0.0.0.0`
