### ISSUE TITLE
Do you have any chance of having an instance without a backdoor?

### ISSUE THREAD

**Issue by nulledone** [ganlvtech/lua-simple-encrypt#33]
Or rather how trustable are you? How much would someone need to pay you for decrypting a lua?

**Comment by ganlvtech** [comment]
1. The backdoor encrypt original password by RSA1024. I won't share private key with others.
2. Don't trust me. It's only an open source web page. You can use it for free. And I'm not responsible for its security.
3. Now, I don't need anyone's payment. I like some interesting encryption design. And I enjoy decrypting such things.
4. I don't like to decrypting for others. If someone ask me to decrypt, my reply maybe arrives several weeks later.
